# Rendered by Omarchy from the selected theme, never sourced as shell code.
mode = "{{ mode }}"
foreground = "{{ foreground }}"
background = "{{ background }}"
accent = "{{ accent }}"
muted = "{{ muted }}"
error = "{{ red }}"
status_background = "{{ mix background foreground 55% }}"
prompt_accent = "{{ accent }}"
prompt_text = "{{ background }}"
prompt_segment = "{{ mix background accent 25% }}"
git_segment = "{{ mix background foreground 65% }}"
runtime_segment = "{{ background }}"
runtime_segment_alt = "{{ mix background foreground 5% }}"
hostname = "{{ orange }}"
node = "{{ green }}"
