# Catppuccin Mocha palette, copied from catppuccin/tmux v2.1.3 (MIT)
# https://github.com/catppuccin/tmux/blob/v2.1.3/themes/catppuccin_mocha_tmux.conf

set -ogq @bg "#1e1e2e"
set -ogq @fg "#cdd6f4"

# Colors
set -ogq @rosewater "#f5e0dc"
set -ogq @flamingo "#f2cdcd"
set -ogq @pink "#f5c2e7"
set -ogq @mauve "#cba6f7"
set -ogq @red "#f38ba8"
set -ogq @maroon "#eba0ac"
set -ogq @peach "#fab387"
set -ogq @yellow "#f9e2af"
set -ogq @green "#a6e3a1"
set -ogq @teal "#94e2d5"
set -ogq @sky "#89dceb"
set -ogq @sapphire "#74c7ec"
set -ogq @blue "#89b4fa"
set -ogq @lavender "#b4befe"

# Surfaces and overlays
set -ogq @subtext_1 "#a6adc8"
set -ogq @subtext_0 "#bac2de"
set -ogq @overlay_2 "#9399b2"
set -ogq @overlay_1 "#7f849c"
set -ogq @overlay_0 "#6c7086"
set -ogq @surface_2 "#585b70"
set -ogq @surface_1 "#45475a"
set -ogq @surface_0 "#313244"
set -ogq @mantle "#181825"
set -ogq @crust "#11111b"
