vim.keymap.set({ "i" }, "kj", "<Esc>")
vim.keymap.set("n", "<C-c>", "<cmd>:noh<cr>")
vim.keymap.set("n", "<leader><space>", "<cmd>buffers<cr>:buffer<Space>")
vim.keymap.set("n", "<leader>d", "<cmd>bd<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>E", "<cmd>Explore<cr>")
vim.keymap.set("n", "<leader>e", "<cmd>e.<cr>")
vim.keymap.set("n", "<leader>n", "<cmd>bn<cr>")
vim.keymap.set("n", "<leader>p", "<cmd>bp<cr>")
vim.keymap.set("n", "<leader>Q", "<cmd>quitall<cr>")
vim.keymap.set("n", "<leader>q", "<cmd>quit<cr>")
vim.keymap.set("n", "<leader>v", "<cmd>vsp %:p:h<cr>")
vim.keymap.set("n", "<leader>V", "<cmd>vsp .<cr>")
vim.keymap.set("n", "<leader>h", "<cmd>Vexplore!<cr>")
vim.keymap.set("n", "<leader>H", "<cmd>topleft vsplit .<cr>")
vim.keymap.set("n", "<leader>s", "<cmd>Se<cr>")
vim.keymap.set("n", "<leader>S", "<cmd>sp .<cr>")
vim.keymap.set("n", "<leader>t", "<cmd>tabe %:p:h<cr>")
vim.keymap.set("n", "<leader>T", "<cmd>tabe .<cr>")
vim.keymap.set("n", "<leader>w", "<cmd>write<cr>")
vim.keymap.set({ "v" }, "<leader>y", '"+y') -- yank to system clipboard
vim.keymap.set({ "n" }, "<leader>y", '<cmd>let @* = fnamemodify(expand("%"), ":~:.")<cr>') -- yank full path to clipboard
vim.keymap.set({ "n" }, "<leader>Y", '<cmd>let @* = fnamemodify(expand("%"), ":t")<cr>') -- yank filename to clipboard

vim.keymap.set("n", "<leader>dd", function()
	vim.diagnostic.open_float(nil, { source = "always" })
end)
vim.keymap.set("n", "[d", vim.diagnostic.goto_prev)
vim.keymap.set("n", "]d", vim.diagnostic.goto_next)
vim.keymap.set("n", "<leader>dl", vim.diagnostic.setloclist)
vim.keymap.set("n", "<C-n>", "<cmd>cnext<cr>")
vim.keymap.set("n", "<C-p>", "<cmd>cprev<cr>")
vim.keymap.set("n", "<leader>r", "<cmd>set relativenumber!<cr>")
vim.keymap.set("n", "<leader>W", "<cmd>set wrap!<cr>")

vim.keymap.set("n", "<leader>fq", function()
	local qf_open = vim.iter(vim.api.nvim_list_wins()):any(function(win)
		return vim.bo[vim.api.nvim_win_get_buf(win)].filetype == "qf"
	end)
	vim.cmd(qf_open and "cclose" or "copen")
end, { desc = "Toggle quickfix list" })
