return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"c",
			"elixir",
			"heex",
			"html",
			"javascript",
			"lua",
			"markdown",
			"markdown_inline",
			"query",
			"typescript",
			"tsx",
			"vim",
			"vimdoc",
			"yaml",
		},
		sync_install = false,
		highlight = { enable = true },
		indent = { enable = true },
	},
}
